### ISSUE TITLE
metaG - Valerie

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/docs#14]
Follow the template below for the index.rst file that is in the docs folder of the repo for your workflow:
Title of Workflow
(Image)
Workflow overview
Workflow availability
Requirements for Execution
Hardware requirements
Workflow dependencies
Software
Database(s)
Sample dataset(s)
Input
Output
Version history
Point of contact

If you have updated figures please put the editable components of the figures [here](https://drive.google.com/drive/folders/1MEmTMLMPeDMQaF-LYnpJswjVmn9MUFTX) as well as in the documentation 
Please follow the following format for updating your documentation:

**Comment by ssarrafan** [comment]
@kaijli what's the status of this? Is this in progress? Can you complete this by Friday?

**Comment by eecavanna** [comment]
Since the workflow repo doesn't have the actual workflow code in it, it does make sense to me to not add the docs there as that might imply to people that this is a "complete" repo. With that in mind, I'd recommend you put the docs for that workflow (er, that "wrapper workflow") directly in this repo, in:

```
content/nmdc/src/reference
```

You can create a new Markdown document in there. When you open a PR, I'll look into how to add some link to that new document. I don't think it'll appear on the sidebar automatically, nor do I think all of our teammates will necessarily support it being visible in the sidebar.

**Comment by aclum** [comment]
Shouldn't this go in the EDGE repo b/c that is where the end to end WDL is?

**Comment by ssarrafan** [comment]
@aclum @eecavanna @kaijli let's discuss this at the next doc squad meeting? I'll add a post to the slack channel.
