### ISSUE TITLE
metaP - Sam/Cam/Camillo

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/docs#15]
Follow the template below for the index.rst file that is in the docs folder of the repo for your workflow:
Title of Workflow
(Image)
Workflow overview
Workflow availability
Requirements for Execution
Hardware requirements
Workflow dependencies
Software
Database(s)
Sample dataset(s)
Input
Output
Version history
Point of contact

If you have updated figures please put the editable components of the figures [here](https://drive.google.com/drive/folders/1MEmTMLMPeDMQaF-LYnpJswjVmn9MUFTX) as well as in the documentation 
Please follow the following format for updating your documentation:

**Comment by SamuelPurvine** [comment]
So that folder is https://github.com/microbiomedata/metaPro/blob/master/docs/, and the index.rst definitely does not yet reflect this format.

Last I saw @picowatt was working on getting the index file into the right format. 

@GrantFujimoto was editing the diagram that can be found at https://github.com/microbiomedata/workflow_documentation/blob/master/docs/chapters/7_Metaproteomics_index.rst to be closer to what the actual outputs are, and was ready to pass that along to @pdpiehowski for approval. Additionally Grant updated the diagram that includes the Kaiko model so when that gets released we'll have that ready to go when the time comes. I would think Grant can then put that powerpoint over into the location you specify above.

**Comment by picowatt** [comment]
Mostly done. Only the Input and Output portions left to finish.

**Comment by ssarrafan** [comment]
@picowatt what's the status of this? Can you complete this by Friday?

**Comment by picowatt** [comment]
@ssarrafan I have time this afternoon to revisit this, will be done before the end of the day.

**Comment by kaijli** [comment]
@picowatt I uploaded the workflow figures that we chatted about last time https://github.com/microbiomedata/metaPro/pull/75
