### ISSUE TITLE
Add banner to new docs landing page to show that it's under development

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/docs#49]
Please add a banner or other large heading on the new landing page for docs at https://docs.microbiomedata.org/  to clearly show that it's under development and not a live site.  

Also, if we need to change the url to make it harder to find in the interim let's do that too. 

The concern is someone finding the site and thinking it's a live, production site.

**Comment by eecavanna** [comment]
Thanks for creating this ticket.

I'll do three things today to reduce the chances that search engines and people misinterpret the in-development docs site as a production site:

- [ ] 1. Add a robots.txt file to the site, which is [a standard way](https://en.wikipedia.org/wiki/Robots.txt) of telling web crawlers (like the one Google uses to find web pages to add to its search index) that we do not want any pages of our site added; although it is up to the individual search engines to comply.
- [ ] 2. Temporarily disconnect the hostname http://docs.microbiomedata.org from the in-development site. As a result, people that visit http://docs.microbiomedata.org will get a "Not Found" error page, just like they would have at any point before two weeks ago.
- [ ] 3. Add a banner like you suggested. This will be for people who stumble upon the site.

I'll post an update here when all of that is done.

**Comment by eecavanna** [comment]
### Conclusion

1. I added a `robots.txt` file that discourages search engine web crawlers from crawling the in-development website. That file is accessible at https://microbiomedata.github.io/docs/robots.txt.
2. I updated our Cloudflare configuration so that, whenever anyone visits https://docs.microbiomedata.org/, they will be redirected to the [documentation page](https://microbiomedata.org/documentation/) on the NMDC website.
   > Note: This in-development website still accessible at its GitHub Pages-provided URL, https://microbiomedata.github.io/docs/. I also updated the GitHub Pages configuration of the in-development website so that GitHub Pages no longer redirects people from https://microbiomedata.github.io/docs/ to https://docs.microbiomedata.org/ (which it automatically does whenever a custom domain is configured for the website).
4. I added a strip-style banner to the top of the in-development website. It mimics the style of the banner on https://fieldnotes.microbiomedata.org. Here's a screenshot of it:   ![Image](https://github.com/user-attachments/assets/803a7e8a-d3f8-4c5c-b985-5a88a7373811)

FYI: @ssarrafan and @shreddd
